name: Test and publish

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Get packages
        run: pnpm install

      - name: knip
        run: pnpm knip

      - name: Dependency cruiser
        run: pnpm dependencies:ci

      - name: Lint
        run: pnpm lint

      - name: Typescript
        run: pnpm tsc

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') && success()
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org/"

      - name: Get packages
        run: pnpm install

      - name: npm version
        run: npm --version

      - name: Sync version from tag
        run: pnpm version ${GITHUB_REF_NAME#v} --no-git-tag-version

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --ignore-scripts --no-git-checks
